# Your Name or Company
title: Saara S. Castro

# Description of your website. This is used for social sharing.
description:  The beautiful website of artist, poet, craftsperson, cyclist, and avid juggler, Uni Kravitz.

# A brief blurb about yourself
content: Apaixonada por tecnologia, inovação, gestão de pessoas e projetos sociais. 

# Add your social links
social:
  - platform: Lattes
    url: http://lattes.cnpq.br/1200771825712342
  - platform: CV
    url: http://bit.ly/cv-saara-EN
  - platform: Linkedin
    url: https://www.linkedin.com/in/saaracastro/
    
# General settings
# url: http://brianmaierjr.github.com/uni
# baseurl: "/uni" 
markdown: kramdown
sharing_image: photo.png
google_analytics: "UA-58263416-1" # google analytics tracking

#### LAYOUT OPTIONS #####

# Half layout
half_side: right

# Full layout
full_text_position: right # left, right or center
